### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by paulvi** [zapletnev/eclipse-regexp#6]
Please replace `Find` with `Found`

What is the meaning of "Looking at" ?

**Comment by zapletnev** [comment]
Hi @PaulVI,
Thanks for your notices. I have fixed typo and fix will be included in v0.4. 
"Looking at" is a flag that shows that the prefix of the input sequence matches this pattern. Only in this case "looking at" will be evaluated as True.

**Comment by paulvi** [comment]
to be changed into "matches" ..? 

I guess should be thought in wider scope #4

**Comment by zapletnev** [comment]
@PaulVI 
"Matches" – True if, and only if, the entire region sequence matches this matcher's pattern
"Looking at" – True if, and only if, a prefix of the input sequence matches this matcher's pattern

**Comment by paulvi** [comment]
Is it input ...
- "Matches wholly"
- "Beginning matches"
  ?

In any case, please append in README

**Comment by zapletnev** [comment]
@PaulVI I have looked at other tools for working with regular expressions, looks like LookingAt only java-specific matcher result. It may be confused for many people. So I have created issue #8 to remove this section. Thanks for your participation!
